name: 同步 d12frosted/elpa-mirror

on:
  push:
  schedule:
    - cron: "0 8 * * *"

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Setup git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Prepare
        run: |
          git clone https://xuchunyang:$GITEE_TOKEN@gitee.com/xuchunyang/elpa-mirror.git
          cd elpa-mirror
          git remote -v
          date >> date.txt
          git add .
          git commit -m 'update'
          git push

      - name: Checkout
        run: |
          pwd
          cd elpa-mirror
          git checkout --orphan mirror

      - name: Add files
        run: |
          git clone --depth 1 https://github.com/d12frosted/elpa-mirror.git
          cd elpa-mirror
          rm -rf .git
          cd ..

          git add .
          git commit -m 'Update with github action'

      - name: Push
        run: |
          git remote add gitee https://xuchunyang:$GITEE_TOKEN@gitee.com/xuchunyang/elpa-mirror.git
          git remote -v
          git push --force gitee mirror
