name: 同步 d12frosted/elpa-mirror

on:
  push:
  schedule:
    - cron: "0 8 * * *"

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror
        run: |
          git clone https://xuchunyang:$GITEE_TOKEN@gitee.com/xuchunyang/elpa-mirror.git
          cd elpa-mirror

          git checkout --orphan mirror

          git clone --depth 1 https://github.com/d12frosted/elpa-mirror.git
          cd elpa-mirror
          rm -rf .git
          cd ..

          git add .
          git commit -m 'Update with github action'
          git push --force origin mirror
